apiVersion: v1
kind: ServiceAccount
metadata:
  name: hello-world
  namespace: hello-world
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: hello-world
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "delete", "update", "list"]
- apiGroups: ["example.com"]
  resources: ["helloworlds"]
  verbs: ["get","watch", "update", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: hello-world
subjects:
- kind: ServiceAccount
  name: hello-world
  namespace: hello-world
roleRef:
  kind: ClusterRole
  name: hello-world
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: helloworlds.example.com
spec:
  group: example.com
  version: v1
  names:
    kind: HelloWorld
    plural: helloworlds
    singular: helloworld
  scope: Namespaced