apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: compositecontrollers.metac.openebs.io
spec:
  group: metac.openebs.io
  version: v1alpha1
  scope: Cluster
  names:
    plural: compositecontrollers
    singular: compositecontroller
    kind: CompositeController
    shortNames:
    - cc
    - cctl
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: decoratorcontrollers.metac.openebs.io
spec:
  group: metac.openebs.io
  version: v1alpha1
  scope: Cluster
  names:
    plural: decoratorcontrollers
    singular: decoratorcontroller
    kind: DecoratorController
    shortNames:
    - dec
    - dectl
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: controllerrevisions.metac.openebs.io
spec:
  group: metac.openebs.io
  version: v1alpha1
  scope: Namespaced
  names:
    plural: controllerrevisions
    singular: controllerrevision
    kind: ControllerRevision
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: genericcontrollers.metac.openebs.io
spec:
  group: metac.openebs.io
  version: v1alpha1
  scope: Namespaced
  names:
    plural: genericcontrollers
    singular: genericcontroller
    kind: GenericController
    shortNames:
    - genctl
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.openebs.io/name: metac
  name: metac
  namespace: metac
spec:
  replicas: 1
  selector:
    matchLabels:
      app.openebs.io/name: metac
  serviceName: ""
  template:
    metadata:
      labels:
        app.openebs.io/name: metac
    spec:
      serviceAccountName: metac
      containers:
      - name: metac
        image: quay.io/amitkumardas/metac:latest
        command: ["/usr/bin/metac"]
        args:
        - --logtostderr
        - -v=6
        - --discovery-interval=20s
      imagePullSecrets:
      - name: amitkumardas-pull-secret
  volumeClaimTemplates: []
