apiVersion: v1
kind: Namespace
metadata:
  name: amitd
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: coolnerds.examples.metac.io
spec:
  group: examples.metac.io
  version: v1
  scope: Namespaced
  names:
    plural: coolnerds
    singular: coolnerd
    kind: CoolNerd
---