apiVersion: v1
kind: ServiceAccount
metadata:
  name: set-status-on-cr
  namespace: set-status-on-cr
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: set-status-on-cr
rules:
- apiGroups:
  - examples.metac.io
  resources:
  - coolnerds
  verbs:
  - get
  - list
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: set-status-on-cr
subjects:
- kind: ServiceAccount
  name: set-status-on-cr
  namespace: set-status-on-cr
roleRef:
  kind: ClusterRole
  name: set-status-on-cr
  apiGroup: rbac.authorization.k8s.io
---