apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: noops.metac.openebs.io
spec:
  group: metac.openebs.io
  version: v1
  scope: Namespaced
  names:
    plural: noops
    singular: noop
    kind: Noop
  subresources:
    status: {}
---
apiVersion: metac.openebs.io/v1alpha1
kind: DecoratorController
metadata:
  name: noop-controller
spec:
  resources:
  # we are interested for noops resource only
  - apiVersion: metac.openebs.io/v1
    resource: noops
  hooks:
    sync:
      webhook:
        url: http://noop-controller.metac/sync
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: noop-controller
  namespace: metac
spec:
  replicas: 1
  selector:
    matchLabels:
      app: noop-controller
  template:
    metadata:
      labels:
        app: noop-controller
    spec:
      containers:
      - name: controller
        image: metacontroller/nodejs-server:0.1
        imagePullPolicy: Always
        volumeMounts:
        - name: hooks
          mountPath: /node/hooks
      volumes:
      - name: hooks
        configMap:
          name: noop-controller
     
---
apiVersion: v1
kind: Service
metadata:
  name: noop-controller
  namespace: metac
spec:
  selector:
    app: noop-controller
  ports:
  - port: 80
