# Override args for development mode.
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: metac
  namespace: metac
spec:
  template:
    spec:
      containers:
      - name: metac
        args:
        - --logtostderr
        - -v=5
        - --discovery-interval=5s
