# Override image for development mode (skaffold fills in the tag).
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: metac
  namespace: metac
spec:
  template:
    spec:
      containers:
      - name: metac
        image: quay.io/amitkumardas/metac:latest
