apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: things.examples.metac.io
spec:
  group: examples.metac.io
  version: v1
  scope: Namespaced
  names:
    plural: things
    singular: thing
    kind: Thing
---
apiVersion: v1
kind: Namespace
metadata:
  name: metacontroller
---
apiVersion: metac.openebs.io/v1alpha1
kind: CompositeController
metadata:
  name: thing-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: examples.metac.io/v1
    resource: things
  childResources:
    - apiVersion: v1
      resource: pods
  hooks:
    sync:
      webhook:
        url: http://thing-controller.metacontroller/sync
---
  # apiVersion: metac.openebs.io/v1alpha1
  # kind: GenericController
  # metadata:
  #   name: set-status-on-cr
  # spec:
  #   watch:
  #     apiVersion: examples.metac.io/v1
  #     resource: coolnerds
  #   hooks:
  #     sync:
  #       inline:
  #         funcName: sync/cool-nerd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thing-controller
  namespace: metacontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thing-controller
  template:
    metadata:
      labels:
        app: thing-controller
    spec:
      containers:
      - name: controller
        image: rahulchheda1997/thing-controller:ci
        command: ["thing-controller"]
---
apiVersion: v1
kind: Service
metadata:
  name: thing-controller
  namespace: metacontroller
spec:
  selector:
    app: thing-controller
  ports:
  - port: 80
    targetPort: 8080
