{{ if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "metac.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "metac.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "metac.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{ end }}
