apiVersion: metac.openebs.io/v1alpha1
kind: GenericController
metadata:
  name: uninstall-openebs
spec:
  # controller should be able to update attachments
  # i.e. remove finalizers if any
  updateAny: true
  # controller should be able to remove attachments
  # i.e. remove custom resources & then their definitions
  deleteAny: true
  # controller keeps a watch on namespace resource
  watch:
    apiVersion: v1
    resource: namespaces
    nameSelector:
    # controller needs to deal with openebs namespace only
    - openebs
  attachments:
  - apiVersion: apiextensions.k8s.io/v1beta1
    resource: customresourcedefinitions
    # controller needs to deal with openebs CRDs only
    nameSelector:
    - castemplates.openebs.io
    - runtasks.openebs.io
    - storagepoolclaims.openebs.io
    - cstorpoolinstances.openebs.io
    - storagepools.openebs.io
    - cstorpools.openebs.io
    - cstorvolumes.openebs.io
    - cstorvolumeclaims.openebs.io
    - cstorvolumereplicas.openebs.io
    - cstorbackups.openebs.io
    - cstorcompletedbackups.openebs.io
    - cstorrestores.openebs.io
    - upgradetasks.openebs.io
    updateStrategy:
      method: InPlace
  # controller needs to deal with openebs custom resources only
  - apiVersion: openebs.io/v1alpha1
    resource: castemplates
    updateStrategy:
      method: InPlace
  - apiVersion: openebs.io/v1alpha1
    resource: runtasks
    updateStrategy:
      method: InPlace
  - apiVersion: openebs.io/v1alpha1
    resource: storagepoolclaims
    updateStrategy:
      method: InPlace
  - apiVersion: openebs.io/v1alpha1
    resource: cstorpoolinstances
    updateStrategy:
      method: InPlace
  - apiVersion: openebs.io/v1alpha1
    resource: storagepools
    updateStrategy:
      method: InPlace
  - apiVersion: openebs.io/v1alpha1
    resource: cstorpools
    updateStrategy:
      method: InPlace
  - apiVersion: openebs.io/v1alpha1
    resource: cstorvolumes
    updateStrategy:
      method: InPlace
  - apiVersion: openebs.io/v1alpha1
    resource: cstorvolumeclaims
    updateStrategy:
      method: InPlace
  - apiVersion: openebs.io/v1alpha1
    resource: cstorvolumereplicas
    updateStrategy:
      method: InPlace
  - apiVersion: openebs.io/v1alpha1
    resource: cstorbackups
    updateStrategy:
      method: InPlace
  - apiVersion: openebs.io/v1alpha1
    resource: cstorcompletedbackups
    updateStrategy:
      method: InPlace
  - apiVersion: openebs.io/v1alpha1
    resource: cstorrestores
    updateStrategy:
      method: InPlace
  - apiVersion: openebs.io/v1alpha1
    resource: upgradetasks
    updateStrategy:
      method: InPlace
  hooks:
    # controller gets triggered only when the watch resource
    # i.e. openebs namespace is being deleted
    finalize:
      inline:
        funcName: finalize/namespace